Update and rename openvpn-01.sh to openvpn-012sh

diff --git a/shell/openvpn-012sh b/shell/openvpn-012sh
--- a/shell/openvpn-012sh
+++ b/shell/openvpn-012sh
@@ -1,7 +1,8 @@
 #!/bin/bash
 # BY: Joseph
 
-# USSAGE="curl https://raw.githubusercontent.com/xyz71148/utils/master/shell/openvpn-01.sh | bash -s $OPEN_VPN_PORT $OPEN_VPN_PWD $REPORT_URL $UPLOAD"
+
+# USSAGE="curl https://raw.githubusercontent.com/xyz71148/utils/master/shell/openvpn-02.sh | bash -s $OPEN_VPN_PORT $OPEN_VPN_PWD $REPORT_URL $UPLOAD"
 
 
 OPEN_VPN_PORT=$1
@@ -10,8 +11,8 @@ REPORT_URL=$3
 UPLOAD=$4
 
 HOST="$(dig +short myip.opendns.com @resolver1.opendns.com)"
-HOST_NAME=${HOST//./_} 
-OVPN_DATA='ovpn-data'       
+HOST_NAME=${HOST//./_}
+OVPN_DATA='ovpn-data'
 
 echo "========================"
 echo $OPEN_VPN_PORT
@@ -27,6 +28,7 @@ if test -f "$FILE"; then
 	  sudo docker ps
     exit 1
 fi
+
 sudo apt-get install -y expect
 sudo docker rm -f $OVPN_DATA
 sudo docker run --name $OVPN_DATA -v /etc/openvpn busybox
@@ -37,7 +39,7 @@ TMP=$(mktemp)
 cat > $TMP << EOF 
 #exp_internal 1 # Uncomment for debug
 set timeout -1
-spawn sudo docker run --volumes-from $OVPN_DATA kylemanna/openvpn ovpn_initpki
+spawn sudo docker run -it --volumes-from $OVPN_DATA kylemanna/openvpn ovpn_initpki
 #expect -exact "Confirm removal:"
 #send -- "yes\r"
 expect -exact "Enter New CA Key Passphrase:"
@@ -54,18 +56,22 @@ expect eof
 EOF
 echo "========================"
 
-cat $TMP && expect -f $TMP && rm $TMP
+cat $TMP
+expect -f $TMP || (echo "ovpn_initpki failed"; exit 1);
+rm $TMP
 echo "========================"
 
 cat  > $TMP << EOF 
 #exp_internal 1 # Uncomment for debug
-spawn sudo docker run --volumes-from $OVPN_DATA kylemanna/openvpn easyrsa build-client-full $HOST_NAME nopass
+spawn sudo docker run -it --volumes-from $OVPN_DATA kylemanna/openvpn easyrsa build-client-full $HOST_NAME nopass
 expect -exact "Enter pass phrase for /etc/openvpn/pki/private/ca.key"
 send -- "$OPEN_VPN_PWD\r"
 expect eof
 EOF
 
-cat $TMP && expect -f $TMP && rm $TMP
+cat $TMP
+expect -f $TMP || (echo "ovpn_initpki failed"; exit 1);
+rm $TMP
 echo "========================"
 
 mkdir -p ~/ovpn
